@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Person(prestadorTrans, "Prestadores de serviço de transporte", "Um prestador de serviço que utiliza app SwiftSend, que leva clientes ao seu destino.")
Person(prestadorEncon, "Prestadores de serviço de encomendas", "Um prestador de serviço que utiliza app SwiftSend, que entrega encomendas de seus clientes.")
System_Ext(gps, "Sistema de mapa e geolocalização")
Container(api, "API Application", "Java Spring Boot", "Providência e recebe os dados via JSON/HTTPS.")

Container_Boundary(mobile, "Mobile App Prestador") {
    Component(criarConta, "Criar conta", "Permite que os usuários realizem o cadastro no sistema")
    Component(login, "Login", "Permite que os usuários façam login no sistema")
    Component(aprovarRecusarServico, "Aprovar ou recusar serviço", "Permite que os usuários aprovem ou recusem solicitações de serviço")
    Component(historicoServicosPrestados, "Historico de serviços prestados", "Permite que os usuários visualizem o historico de serviços prestados")
    Component(cancelarServico, "Cancelar serviço", "Permite que os usuários cancelem a solicitação de um serviço")
    Component(finalizarServico, "Finalizar serviço", "Permite que os usuários indiquem a finalização de um serviço")
    Component(perfilPrestador, "Perfil do Prestador", "Permite que os usuários visualizem e alterem o cadastro no sistema")

    Rel(login, criarConta, "É obrigatorio ")
    Rel(aprovarRecusarServico, login, "É obrigatorio realizar")
    Rel(cancelarServico, aprovarRecusarServico, "Utiliza")
    Rel(finalizarServico, aprovarRecusarServico, "Utiliza")
    Rel(perfilPrestador, historicoServicosPrestados, "Permite visualizar")
    Rel(perfilPrestador, login, "Utiliza")
}

Rel(prestadorEncon, login, "Pode realizar")
Rel(prestadorEncon, criarConta, "Pode")
Rel(prestadorEncon, aprovarRecusarServico, "Pode")

Rel(prestadorTrans, aprovarRecusarServico, "Pode")
Rel(prestadorTrans, login, "Pode realizar")
Rel(prestadorTrans, criarConta, "Pode")

Rel(login, api, "Consome dados da")
Rel(criarConta, api, "Envia dados para")
Rel(historicoServicosPrestados, api, "Consome dado da")
Rel(perfilPrestador, api, "Manipula dado da")
Rel(aprovarRecusarServico, api, "Manipula dado da")

Rel(aprovarRecusarServico, gps, "Intrega o")


@enduml
