@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(passageiro, "Passageiro", "Um cliente, usuário do aplicativo SwiftSend")
Person(motorista, "Motorista", "Um prestador de serviço que utiliza app SwiftSend")
System(swift, "SwiftSend", "Aplicativo de intermediação entre prestadores de serviços e seus clientes")
System_Ext(bank, "Sistema de cobraças")
System_Ext(gps, "Sistema de mapa e geolocalização")

Rel(passageiro, swift, "Usa")
Rel(motorista, swift, "Atende")
Rel(swift, bank, "Se utiliza de")
Rel(swift, gps, "Se utiliza de")
@enduml
